version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: "ricimon.com-dev"
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - ./:/src
      - '/src/node_modules'
